import postgres from "postgres";
import * as dotenv from "dotenv";
import crypto from "crypto";

dotenv.config({ path: ".env.local" });
if (!process.env.DATABASE_URL) dotenv.config({ path: ".env" });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("❌ DATABASE_URL is not set");
  process.exit(1);
}

const sql = postgres(connectionString, { prepare: false });

export const CATEGORIES = [
  { id: "cat-easy", name: "Easy connection", slug: "easy", sortOrder: 1, stageAffinity: "All Stages" },
  { id: "cat-baby", name: "Play date", slug: "baby", sortOrder: 2, stageAffinity: "Babies" },
  { id: "cat-evenings", name: "MoM's date", slug: "evenings", sortOrder: 3, stageAffinity: "Moms Only" },
  { id: "cat-learn", name: "Learn & Grow", slug: "learn", sortOrder: 4, stageAffinity: "All Stages" },
  { id: "cat-signature", name: "Signature moments", slug: "signature", sortOrder: 5, stageAffinity: "All Stages" },
];

export const PARTNERS = [
  {
    id: "terraza-sarria",
    name: "Terraza Sarrià",
    umbrella: "Places & Hospitality",
    specialty: "Rooftop dining & private events",
    description: "A seasonal courtyard and rooftop space for special club moments.",
    offerForMembers: "Exclusive private room booking and priority reservations.",
  },
  {
    id: "loto-barcelona-yoga",
    name: "Loto Barcelona Yoga",
    umbrella: "Wellness & Movement",
    specialty: "Postnatal & prenatal yoga",
    description: "Gentle postnatal and perinatal movement studio in Gràcia.",
    offerForMembers: "15% discount on class packages.",
  },
  {
    id: "can-culleretes",
    name: "Can Culleretes",
    umbrella: "Places & Hospitality",
    specialty: "Traditional Catalan dining",
    description: "Barcelona's oldest restaurant, hosting private MoM's dates.",
    offerForMembers: "Complimentary drink on arrival for member bookings.",
  },
  {
    id: "vermuteria-bonavista",
    name: "Vermuteria Bonavista",
    umbrella: "Places & Hospitality",
    specialty: "Aperitivo & artisan vermut",
    description: "Cozy neighbourhood vermuteria in Gràcia.",
    offerForMembers: "Reserved back room and complimentary tapa.",
  },
  {
    id: "dorm-be-sleep-consultants",
    name: "Dorm Bé Sleep Consultants",
    umbrella: "Expert Care & Support",
    specialty: "Pediatric sleep consulting",
    description: "Certified pediatric sleep consultants helping families rest.",
    offerForMembers: "20% discount on 1-on-1 consultations.",
  },
  {
    id: "petit-toucher",
    name: "Petit Toucher",
    umbrella: "Baby & Child Activities",
    specialty: "Infant massage & sensory play",
    description: "Gentle baby massage and sensory development workshops.",
    offerForMembers: "10% off workshop series.",
  },
  {
    id: "momentum-careers-barcelona",
    name: "Momentum Careers Barcelona",
    umbrella: "Expert Care & Support",
    specialty: "Career transition & return to work",
    description: "Supporting mothers navigating the return to work.",
    offerForMembers: "Free 30-minute career audit.",
  },
  {
    id: "sala-gracia",
    name: "Sala Gràcia",
    umbrella: "Places & Hospitality",
    specialty: "Private dining & tastings",
    description: "Intimate private dining rooms for special gatherings.",
    offerForMembers: "No room hire fee for member private dinners.",
  },
  {
    id: "casa-aribau",
    name: "Casa Aribau",
    umbrella: "Wellness & Movement",
    specialty: "Perinatal osteopathy & wellness",
    description: "Specialized perinatal health and osteopathy clinic.",
    offerForMembers: "15% off first treatment session.",
  },
  {
    id: "babylatch-consultants",
    name: "BabyLatch Consultants",
    umbrella: "Expert Care & Support",
    specialty: "Lactation support & feeding circles",
    description: "Certified IBCLC lactation consultants and feeding circles.",
    offerForMembers: "Priority home visit booking.",
  },
];

export const EVENTS = [
  {
    id: "event-13",
    slug: "summer-supper-in-the-courtyard-13",
    title: "Signature moment — Summer supper in the courtyard",
    categoryId: "cat-signature",
    description: "A long table under the fig tree, one menu, no phones. Our first supper of the summer.",
    meetingPoint: "Carrer de Sant Domènec 12 — the courtyard door",
    neighbourhood: "Gràcia",
    venueName: "Terraza Sarrià",
    partnerId: "terraza-sarria",
    startsAt: "2026-08-10T20:30:00.000Z",
    endsAt: "2026-08-10T23:00:00.000Z",
    creditCost: 55,
    guestPriceCents: 3500,
    capacityMember: 14,
    capacityGuest: 0,
    minToConfirm: 8,
    isSignature: true,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "completed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 14,
  },
  {
    id: "event-1",
    slug: "morning-walk-ciutadella-park-1",
    title: "Morning walk — Ciutadella Park",
    categoryId: "cat-easy",
    description: "A relaxed stroller walk through the park, followed by coffee nearby.",
    meetingPoint: "Passeig de Picasso 21 — Arc de Triomf gate, look for the cream Mothers tote",
    neighbourhood: "Ciutat Vella",
    venueName: "Parc de la Ciutadella",
    partnerId: null,
    startsAt: "2026-08-19T10:00:00.000Z",
    endsAt: "2026-08-19T11:30:00.000Z",
    creditCost: 0,
    guestPriceCents: 0,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 3,
    isSignature: false,
    isFreeWalk: true,
    childcare: "child_inclusive",
    status: "completed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 12,
  },
  {
    id: "event-12",
    slug: "park-social-turo-park-lawn-12",
    title: "Park social — Turó Park lawn",
    categoryId: "cat-easy",
    description: "Blankets on the grass, snacks to share, and no schedule — come for ten minutes or stay until the light goes.",
    meetingPoint: "Av. de Pau Casals 19 — lawn beside the pond",
    neighbourhood: "Sarrià-Sant Gervasi",
    venueName: "Turó Park",
    partnerId: null,
    startsAt: "2026-09-02T17:30:00.000Z",
    endsAt: "2026-09-02T19:30:00.000Z",
    creditCost: 0,
    guestPriceCents: 0,
    capacityMember: 16,
    capacityGuest: 4,
    minToConfirm: 0,
    isSignature: false,
    isFreeWalk: true,
    childcare: "child_inclusive",
    status: "confirmed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 8,
  },
  {
    id: "event-2",
    slug: "play-date-postnatal-yoga-2",
    title: "Play date — Postnatal yoga",
    categoryId: "cat-baby",
    description: "Gentle postnatal yoga with your baby beside you, led by a certified instructor.",
    meetingPoint: "Carrer de Verdi 42, 2º — buzzer “Loto”",
    neighbourhood: "Gràcia",
    venueName: "Loto Barcelona Yoga",
    partnerId: "loto-barcelona-yoga",
    startsAt: "2026-08-21T10:30:00.000Z",
    endsAt: "2026-08-21T11:45:00.000Z",
    creditCost: 18,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 5,
    isSignature: false,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "completed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 12,
  },
  {
    id: "event-3",
    slug: "moms-date-dinner-at-can-culleretes-3",
    title: "MoM's date — Dinner at Can Culleretes",
    categoryId: "cat-evenings",
    description: "A relaxed dinner for mothers only — no kid talk required.",
    meetingPoint: "Carrer d'en Quintana 5 — ask for The Mothers table",
    neighbourhood: "Ciutat Vella",
    venueName: "Can Culleretes",
    partnerId: "can-culleretes",
    startsAt: "2026-08-27T20:00:00.000Z",
    endsAt: "2026-08-27T22:30:00.000Z",
    creditCost: 20,
    guestPriceCents: 3500,
    capacityMember: 10,
    capacityGuest: 2,
    minToConfirm: 6,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "completed",
    languages: ["es", "en", "fr"],
    showEventPassCta: true,
    initialBookings: 10,
  },
  {
    id: "event-20",
    slug: "moms-date-vermut-on-bonavista-20",
    title: "MoM's date — Vermut on Bonavista",
    categoryId: "cat-evenings",
    description: "An early evening over vermut and olives. Small table, no agenda, home by ten.",
    meetingPoint: "Carrer de Bonavista 6 — the back room, ask for The Mothers",
    neighbourhood: "Gràcia",
    venueName: "Vermuteria Bonavista",
    partnerId: "vermuteria-bonavista",
    startsAt: "2026-09-10T19:30:00.000Z",
    endsAt: "2026-09-10T21:30:00.000Z",
    creditCost: 14,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 6,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "confirmed",
    languages: ["es", "en"],
    showEventPassCta: true,
    initialBookings: 7,
  },
  {
    id: "event-4",
    slug: "learn-grow-sleep-qa-with-an-expert-4",
    title: "Learn & Grow — Sleep Q&A with an expert",
    categoryId: "cat-learn",
    description: "A pediatric sleep consultant answers your toughest nighttime questions.",
    meetingPoint: "Carrer de Pau Claris 138, 1º-2ª — Dorm Bé studio",
    neighbourhood: "Eixample",
    venueName: "Dorm Bé studio",
    partnerId: "dorm-be-sleep-consultants",
    startsAt: "2026-09-01T18:00:00.000Z",
    endsAt: "2026-09-01T19:30:00.000Z",
    creditCost: 12,
    guestPriceCents: 3500,
    capacityMember: 16,
    capacityGuest: 2,
    minToConfirm: 14,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "published_pending",
    languages: ["en"],
    showEventPassCta: false,
    initialBookings: 11,
  },
  {
    id: "event-5",
    slug: "signature-moment-autumn-rooftop-brunch-5",
    title: "Signature moment — Autumn rooftop brunch",
    categoryId: "cat-signature",
    description: "A seasonal rooftop brunch with live music, for members and their little ones.",
    meetingPoint: "Carrer de Cardenal Sentmenat 30 — rooftop, 7th floor",
    neighbourhood: "Sarrià-Sant Gervasi",
    venueName: "Terraza Sarrià",
    partnerId: "terraza-sarria",
    startsAt: "2026-09-12T11:00:00.000Z",
    endsAt: "2026-09-12T14:00:00.000Z",
    creditCost: 55,
    guestPriceCents: 3500,
    capacityMember: 20,
    capacityGuest: 0,
    minToConfirm: 10,
    isSignature: true,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "published_pending",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 8,
  },
  {
    id: "event-6",
    slug: "stroller-walk-park-guell-area-6",
    title: "Stroller walk — Park Güell area",
    categoryId: "cat-easy",
    description: "An easy-paced walk near the park, with a stop for snacks halfway through.",
    meetingPoint: "Carrer d'Olot 5 — steps at the main gate",
    neighbourhood: "Gràcia",
    venueName: "Park Güell",
    partnerId: null,
    startsAt: "2026-09-16T10:00:00.000Z",
    endsAt: "2026-09-16T11:30:00.000Z",
    creditCost: 0,
    guestPriceCents: 0,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 4,
    isSignature: false,
    isFreeWalk: true,
    childcare: "child_inclusive",
    status: "confirmed",
    languages: ["es", "ca"],
    showEventPassCta: false,
    initialBookings: 6,
  },
  {
    id: "event-7",
    slug: "play-date-baby-massage-class-7",
    title: "Play date — Baby massage class",
    categoryId: "cat-baby",
    description: "Learn simple massage techniques to soothe and bond with your baby.",
    meetingPoint: "Carrer del Comandant Benítez 11 — studio B",
    neighbourhood: "Les Corts",
    venueName: "Petit Toucher",
    partnerId: "petit-toucher",
    startsAt: "2026-09-21T11:00:00.000Z",
    endsAt: "2026-09-21T12:15:00.000Z",
    creditCost: 18,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 8,
    isSignature: false,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "published_pending",
    languages: ["es", "en"],
    showEventPassCta: true,
    initialBookings: 5,
  },
  {
    id: "event-8",
    slug: "learn-grow-returning-to-work-panel-8",
    title: "Learn & Grow — Returning to work panel",
    categoryId: "cat-learn",
    description: "A panel of working mothers share honest advice on the return to work.",
    meetingPoint: "Zoom — link sent when you book",
    neighbourhood: "Eixample",
    venueName: "Zoom",
    partnerId: "momentum-careers-barcelona",
    startsAt: "2026-10-01T18:30:00.000Z",
    endsAt: "2026-10-01T20:00:00.000Z",
    creditCost: 12,
    guestPriceCents: 3500,
    capacityMember: 25,
    capacityGuest: 2,
    capacityGuestGathering: 5,
    minToConfirm: 14,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "published_pending",
    languages: ["en"],
    showEventPassCta: true,
    initialBookings: 6,
  },
  {
    id: "event-10",
    slug: "hosted-coffee-gracia-10",
    title: "Hosted coffee — Gràcia",
    categoryId: "cat-easy",
    description: "A booked table, a host who introduces everyone, and a coffee waiting for you. Eight mothers, no small talk to start from scratch.",
    meetingPoint: "Plaça de la Vila de Gràcia 12 — reserved table on the terrace",
    neighbourhood: "Gràcia",
    venueName: "Can Culleretes",
    partnerId: "can-culleretes",
    startsAt: "2026-08-25T10:30:00.000Z",
    endsAt: "2026-08-25T12:00:00.000Z",
    creditCost: 2,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 4,
    isSignature: false,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "completed",
    languages: ["es"],
    showEventPassCta: false,
    initialBookings: 12,
  },
  {
    id: "event-11",
    slug: "hosted-brunch-eixample-11",
    title: "Hosted brunch — Eixample",
    categoryId: "cat-easy",
    description: "The same easy format over brunch: a table held for us, a host at the centre, and one drink included.",
    meetingPoint: "Carrer del Consell de Cent 333 — back room, under the skylight",
    neighbourhood: "Eixample",
    venueName: "Carrer del Consell de Cent",
    partnerId: null,
    startsAt: "2026-09-09T11:00:00.000Z",
    endsAt: "2026-09-09T13:00:00.000Z",
    creditCost: 2,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 4,
    minToConfirm: 4,
    isSignature: false,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "confirmed",
    languages: ["es", "en", "fr"],
    showEventPassCta: true,
    initialBookings: 5,
  },
  {
    id: "event-23",
    slug: "learn-grow-asking-for-what-you-need-at-home-23",
    title: "Learn & Grow — Asking for what you need at home",
    categoryId: "cat-learn",
    description: "Two hours on the conversation nobody rehearses: naming what you need from a partner or a parent, and asking for it plainly.",
    meetingPoint: "Carrer de Sepúlveda 61, entresuelo — studio A",
    neighbourhood: "Sant Antoni",
    venueName: "Carrer de Sepúlveda",
    partnerId: null,
    startsAt: "2026-09-05T11:00:00.000Z",
    endsAt: "2026-09-05T13:00:00.000Z",
    creditCost: 12,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 6,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "confirmed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 11,
  },
  {
    id: "event-22",
    slug: "moms-date-tasting-menu-private-room-22",
    title: "MoM's date — Tasting menu, private room",
    categoryId: "cat-evenings",
    description: "Six courses at one long table, a room of our own, and a night that ends when we say it does.",
    meetingPoint: "Passeig de Gràcia 78, 1º — the private dining room",
    neighbourhood: "Eixample",
    venueName: "Sala Gràcia",
    partnerId: "sala-gracia",
    startsAt: "2026-09-24T20:30:00.000Z",
    endsAt: "2026-09-24T23:30:00.000Z",
    creditCost: 25,
    guestPriceCents: 3500,
    capacityMember: 10,
    capacityGuest: 0,
    minToConfirm: 6,
    isSignature: false,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "confirmed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 6,
  },
  {
    id: "event-21",
    slug: "signature-moment-one-to-one-with-a-perinatal-osteopath-21",
    title: "Signature moment — One-to-one with a perinatal osteopath",
    categoryId: "cat-signature",
    description: "A full private hour with a perinatal osteopath, in a quiet room, for the body that carried and still carries.",
    meetingPoint: "Carrer d'Aribau 112, principal — the treatment suite",
    neighbourhood: "Eixample",
    venueName: "Casa Aribau",
    partnerId: "casa-aribau",
    startsAt: "2026-09-19T10:30:00.000Z",
    endsAt: "2026-09-19T11:30:00.000Z",
    creditCost: 32,
    guestPriceCents: 3500,
    capacityMember: 6,
    capacityGuest: 0,
    minToConfirm: 2,
    isSignature: true,
    isFreeWalk: false,
    childcare: "adults_only",
    status: "confirmed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 4,
  },
  {
    id: "event-9",
    slug: "play-date-newborn-feeding-circle-9",
    title: "Play date — Newborn feeding circle",
    categoryId: "cat-baby",
    description: "A small support circle for feeding questions in the early months, with a lactation consultant on hand.",
    meetingPoint: "Carrer de Girona 84, entresuelo",
    neighbourhood: "Eixample",
    venueName: "BabyLatch Consultants",
    partnerId: "babylatch-consultants",
    startsAt: "2026-08-19T10:00:00.000Z",
    endsAt: "2026-08-19T11:30:00.000Z",
    creditCost: 18,
    guestPriceCents: 3500,
    capacityMember: 12,
    capacityGuest: 2,
    minToConfirm: 4,
    isSignature: false,
    isFreeWalk: false,
    childcare: "child_inclusive",
    status: "completed",
    languages: ["es", "en"],
    showEventPassCta: false,
    initialBookings: 12,
  },
];

async function seed() {
  console.log("🌱 Seeding 17 reference events, categories, and partners...");

  try {
    // 1. Seed categories
    for (const c of CATEGORIES) {
      await sql`
        INSERT INTO event_category (id, name, slug, sort_order, stage_affinity)
        VALUES (${c.id}, ${c.name}, ${c.slug}, ${c.sortOrder}, ${c.stageAffinity})
        ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          slug = EXCLUDED.slug,
          sort_order = EXCLUDED.sort_order,
          stage_affinity = EXCLUDED.stage_affinity;
      `;
    }
    console.log("✅ Categories seeded");

    // 2. Seed partners
    for (const p of PARTNERS) {
      await sql`
        INSERT INTO partner (id, name, umbrella, specialty, description, offer_for_members, status)
        VALUES (${p.id}, ${p.name}, ${p.umbrella}, ${p.specialty}, ${p.description}, ${p.offerForMembers}, 'active')
        ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          umbrella = EXCLUDED.umbrella,
          specialty = EXCLUDED.specialty,
          description = EXCLUDED.description,
          offer_for_members = EXCLUDED.offer_for_members;
      `;
    }
    console.log("✅ Partners seeded");

    // 3. Seed 17 Events
    for (const ev of EVENTS) {
      await sql`
        INSERT INTO event (
          id, title, slug, category_id, description, neighbourhood, venue_name,
          meeting_point, starts_at, ends_at, credit_cost, guest_price_cents,
          capacity_member, capacity_guest, capacity_guest_gathering, min_to_confirm,
          is_signature, is_free_walk, childcare, status, languages, show_event_pass_cta, partner_id
        ) VALUES (
          ${ev.id}, ${ev.title}, ${ev.slug}, ${ev.categoryId}, ${ev.description}, ${ev.neighbourhood}, ${ev.venueName},
          ${ev.meetingPoint}, ${new Date(ev.startsAt)}, ${new Date(ev.endsAt)}, ${ev.creditCost}, ${ev.guestPriceCents},
          ${ev.capacityMember}, ${ev.capacityGuest}, ${ev.capacityGuestGathering || null}, ${ev.minToConfirm},
          ${ev.isSignature}, ${ev.isFreeWalk}, ${ev.childcare}, ${ev.status}, ${ev.languages}, ${ev.showEventPassCta}, ${ev.partnerId}
        )
        ON CONFLICT (id) DO UPDATE SET
          title = EXCLUDED.title,
          slug = EXCLUDED.slug,
          category_id = EXCLUDED.category_id,
          description = EXCLUDED.description,
          neighbourhood = EXCLUDED.neighbourhood,
          venue_name = EXCLUDED.venue_name,
          meeting_point = EXCLUDED.meeting_point,
          starts_at = EXCLUDED.starts_at,
          ends_at = EXCLUDED.ends_at,
          credit_cost = EXCLUDED.credit_cost,
          guest_price_cents = EXCLUDED.guest_price_cents,
          capacity_member = EXCLUDED.capacity_member,
          capacity_guest = EXCLUDED.capacity_guest,
          capacity_guest_gathering = EXCLUDED.capacity_guest_gathering,
          min_to_confirm = EXCLUDED.min_to_confirm,
          is_signature = EXCLUDED.is_signature,
          is_free_walk = EXCLUDED.is_free_walk,
          childcare = EXCLUDED.childcare,
          status = EXCLUDED.status,
          languages = EXCLUDED.languages,
          show_event_pass_cta = EXCLUDED.show_event_pass_cta,
          partner_id = EXCLUDED.partner_id;
      `;
    }
    console.log("✅ 17 Events seeded successfully!");
  } catch (error) {
    console.error("❌ Seeding error:", error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

seed();
